---
# tasks file for db_task

 
 - 
   name: add database
   mysql_db:
     name: fosslinuxzabbix
     state: present
     encoding: utf8
     collation: utf8_bin
     
    
   ignore_errors: yes

 - 
   name: add database user
   mysql_user:
    name: zabbixuser
    host: localhost
    password: "dfEr234KliT90"
    priv: '*.*:ALL,GRANT'
    state: present
   
    
   ignore_errors: yes
 
 
 
   